{{- if .Values.namespace.create }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeflow.namespace" . }}
  labels:
    {{- include "kubeflow.labels" . | nindent 4 }}
    {{- with .Values.namespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "kubeflow.annotations" . | nindent 4 }}
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.syncWaves.namespace | quote }}
    {{- end }}
{{- end }}

{{- if .Values.auth.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeflow.authNamespace" . }}
  labels:
    {{- include "kubeflow.labels" . | nindent 4 }}
    istio-injection: enabled
  annotations:
    {{- include "kubeflow.annotations" . | nindent 4 }}
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.syncWaves.namespace | quote }}
    {{- end }}
{{- end }}

{{- if .Values.auth.oauth2Proxy.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeflow.oauth2ProxyNamespace" . }}
  labels:
    {{- include "kubeflow.labels" . | nindent 4 }}
    istio-injection: enabled
  annotations:
    {{- include "kubeflow.annotations" . | nindent 4 }}
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.syncWaves.namespace | quote }}
    {{- end }}
{{- end }}

{{- if .Values.knative.enabled }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "kubeflow.knativeNamespace" . }}
  labels:
    {{- include "kubeflow.labels" . | nindent 4 }}
  annotations:
    {{- include "kubeflow.annotations" . | nindent 4 }}
    {{- if .Values.argocd.enabled }}
    argocd.argoproj.io/sync-wave: {{ .Values.argocd.syncWaves.namespace | quote }}
    {{- end }}
{{- end }}

