{{- if .Values.loadBalancer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "template.fullname" . }}-lb
  namespace: {{ include "template.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "7"
  labels:
    {{- include "template.labels" . | nindent 4 }}
    app.kubernetes.io/component: loadbalancer
spec:
  type: {{ .Values.loadBalancer.type }}
  {{- if .Values.loadBalancer.loadBalancerIP }}
  loadBalancerIP: {{ .Values.loadBalancer.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.loadBalancer.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "template.selectorLabels" . | nindent 4 }}
{{- end }} 