{{- if and .Values.persistence.enabled (not .Values.persistence.existingClaim) }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "template.pvcName" . }}
  namespace: {{ include "template.namespace" . }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
    app.kubernetes.io/component: storage
  annotations:
    argocd.argoproj.io/sync-wave: "3"
    {{- if .Values.persistence.reclaimPolicy }}
    volume.beta.kubernetes.io/storage-class: {{ .Values.persistence.storageClass | quote }}
    {{- end }}
    {{- with .Values.persistence.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  accessModes:
    - {{ .Values.persistence.accessMode }}
  {{- if .Values.persistence.storageClass }}
  {{- if (eq "-" .Values.persistence.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: {{ .Values.persistence.storageClass }}
  {{- end }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
{{- end }} 