{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "template.serviceAccountName" . }}
  namespace: {{ include "template.namespace" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "template.labels" . | nindent 4 }}
    app.kubernetes.io/component: serviceaccount
automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
{{- end }} 